# Generated by Django 3.0.7 on 2022-06-19 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('style', models.CharField(max_length=64)),
                ('additional', models.CharField(max_length=255)),
                ('is_special', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('added_cost', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('style', models.CharField(max_length=64)),
                ('additional', models.CharField(max_length=255)),
                ('is_special', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastaStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special', models.BooleanField(default=False)),
                ('num_toppings', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SaladStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Dinner_platter',
        ),
        migrations.DeleteModel(
            name='Oder_counter',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Regular_pizza',
        ),
        migrations.RemoveField(
            model_name='user_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='large',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small',
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='DinnerPlatterStyle',
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
        migrations.DeleteModel(
            name='User_order',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaStyle'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_platter', to='orders.Menu'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DinnerPlatterStyle'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.PastaStyle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salad',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salad',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.SaladStyle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='sub',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
            preserve_default=False,
        ),
    ]
